sudo: required
services:
  - docker

before_install:
  - docker build -t beamer .
  - docker run --name builder -td beamer

script:
  - docker exec -ti builder mkdir -p build
  - docker exec -ti builder pdflatex -interaction=nonstopmode -halt-on-error -output-directory build example.tex
  - docker exec -ti builder pdflatex -interaction=nonstopmode -halt-on-error -output-directory build example.tex
  - docker exec -ti builder bash -c 'qpdf build/example.pdf --pages build/example.pdf 1,3 -- - | convert - build/example.png'

before_deploy:
  - docker cp builder:/home/tmp/build ./build
  - git config --local user.name "Patrick Holthaus"
  - git config --local user.email "patrick.holthaus@googlemail.com"

deploy:
  provider: releases
  api_key:
    secure: "D5/yOFTPz9/rbicrMl3wji0xASZBsiAzswkHVHEE0N6PsDfdY1uTTo6bYNgdrfC6JDw2OKmGkO/iuet8o2csqpnOfQ+VWO7/7Ld2TPdGQ3Gq3aIX3cb8IXmWhQmjsZqYeDhMcEnHp1JvjCg+uF2tsS55wYDokzCWmfLCRu3c16KtxvMeLWhdUdB67DY/M2SpcXoTD48f+xZ7u/UV2uXaGKQHkHGkomWH7mH0eMjws9BjqItU1S7ckCY7EYYk6Sj/WHqzt8mr3zrDCP0yEBPsEndzoVLVYGFCxm4t8UbwulHuxHhX6Rys0ojwVZVkDsbfq0W7LQT4si2sawXljV0yzOJv3OhuXgHSaSA5M5ZZ9Leafh/7yxBV5tLVMB/tkh1T8ajTKw5A4Fhvv8ajSdMSRtbrbN5a9ugrzn4KOqEBAHRg7CQL+RveenAeillQgvrRP7Y3BuMnpVh5nDUyt4VIfBF5yH+U8AB7C4Ryp7UifrejOSgNAquO4QPw47N0hggA5XJgr6YrSFz1oojBfDLa6RXjwRlkCJhv0S8AQ1vm5QtPcmA0EpkizheWuGVP/BHrcoUna2o3UyZ4K3GJKuvg87rwDUHdNmCXIRzPMS3pBpZtbeR8Egq6DtdNG0N7Zu9XK49dJGYIAR3V8f1ynOtVocimPqgXvltfzCVLAaIf5Ys="
  skip_cleanup: true
  on:
    tags: true
  file:
    - build/example.pdf
    - build/example-0.png
    - build/example-1.png
